export const TermsAndConditions = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ullamcorper, leo ut sodales hendrerit, risus lacus ultricies turpis, ut dignissim lorem lacus lacinia urna. Proin egestas ex lorem. Sed sed pulvinar tellus, id aliquam elit. Quisque vitae ultrices elit, id faucibus velit. Sed vel enim condimentum, euismod lacus egestas, scelerisque justo. In faucibus, nibh nec luctus ultricies, nisi quam tempus magna, non malesuada nisi lectus eu elit. Phasellus eget egestas orci.

Mauris tempus ipsum est, posuere volutpat dui cursus sed. Pellentesque et maximus orci. Mauris eu tincidunt tellus. Sed a mattis urna. Vivamus sed erat id purus congue convallis cursus vitae nisl. Vestibulum tristique scelerisque ex in ultricies. Quisque vel sem mattis, efficitur lorem et, eleifend lectus. Nam sit amet placerat tortor. Vivamus molestie orci scelerisque placerat semper. Vestibulum rutrum scelerisque nisl vel ultrices. Phasellus arcu nulla, faucibus quis porttitor ut, euismod nec mi. Pellentesque fermentum vestibulum nunc non auctor. Nulla vitae mi imperdiet, consequat mauris vitae, euismod nisi.

Phasellus in risus diam. Aenean suscipit tempor ex, sed feugiat eros pulvinar sit amet. Etiam ac nunc id neque vestibulum ullamcorper ut sed ante. Fusce in tortor leo. Pellentesque id varius ipsum. Mauris non eros gravida, lobortis risus vitae, mattis nisi. Aliquam molestie dictum ligula, quis elementum eros mattis vitae. Etiam vitae metus at leo finibus mattis. Curabitur convallis imperdiet lectus sed vestibulum. Proin in eros feugiat dui volutpat suscipit. Vestibulum laoreet non elit non auctor. Maecenas sit amet neque molestie, maximus mauris et, efficitur justo. Cras feugiat elit ut ante porta vehicula. Aliquam id convallis urna.

Vestibulum pretium id nunc sit amet tincidunt. Nullam consequat nisl orci, ut faucibus nisi efficitur eu. Maecenas eu fermentum quam. Fusce cursus mauris ut mi commodo malesuada. Curabitur sed ex laoreet odio sodales dignissim eget vel mauris. Nam tellus urna, condimentum nec neque eu, eleifend ullamcorper ligula. Proin eget lectus ligula. Donec dignissim ullamcorper lorem, ut vulputate turpis lobortis et. Praesent viverra tempor lorem quis suscipit. Curabitur luctus vel urna eget molestie. Praesent eros lorem, dictum in finibus sit amet, dignissim eget augue. Curabitur vestibulum elit eu dui semper condimentum. Phasellus vel neque in nibh fermentum fringilla nec sit amet lacus.

Integer convallis quam eget dui aliquet, egestas feugiat odio hendrerit. Praesent rhoncus, augue vel hendrerit tempor, nisl augue luctus velit, nec porttitor lacus velit quis metus. Morbi scelerisque viverra pretium. Sed imperdiet congue massa quis dignissim. Cras vestibulum dolor libero, nec ornare libero ultrices quis. Pellentesque viverra massa dolor, vel auctor eros maximus id. Duis vitae massa eget urna porttitor tincidunt. Nam pharetra, odio at suscipit ullamcorper, est lacus interdum enim, a posuere justo mauris sed urna. Curabitur vestibulum vitae est id sagittis. Nunc massa ante, dictum et est eget, viverra viverra velit. Suspendisse potenti. Sed posuere ut lectus non molestie. Donec tempus augue in odio sollicitudin, sit amet convallis velit blandit. In a lorem sodales, fringilla metus in, mollis ex. Etiam consectetur congue dui, vel faucibus purus mollis vitae.

Morbi feugiat sem elit, sodales dapibus arcu mollis et. Nulla tristique accumsan eros, vel sodales nibh accumsan id. In euismod maximus elit nec ornare. Donec varius tristique porttitor. Vestibulum at pulvinar diam, eget pharetra erat. Pellentesque vestibulum arcu in justo varius posuere vel et neque. Integer et purus vitae mauris cursus sagittis quis in purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quis lorem ante. Pellentesque faucibus auctor quam. Maecenas vehicula mi a odio facilisis pharetra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus vulputate aliquet odio. Aenean tincidunt nibh vel tortor auctor, et efficitur mi interdum. Nullam pharetra dolor nibh, quis fermentum nunc iaculis non. Donec tempor nisi tortor, et suscipit odio elementum nec.

Phasellus nec enim mi. Fusce vel felis sed quam malesuada sagittis. Proin efficitur interdum magna, non porta nulla tincidunt et. Integer cursus augue eget maximus fringilla. Suspendisse tristique bibendum urna ut aliquam. Pellentesque sed placerat nunc, at suscipit lorem. Suspendisse faucibus justo maximus dolor dictum, vestibulum scelerisque velit malesuada. Quisque non neque porta, consequat dolor eu, elementum libero. Phasellus in placerat nunc, at congue massa. Vivamus hendrerit urna ligula, non venenatis velit placerat id
`;

export const PrivacyAndPolicies = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ullamcorper, leo ut sodales hendrerit, risus lacus ultricies turpis, ut dignissim lorem lacus lacinia urna. Proin egestas ex lorem. Sed sed pulvinar tellus, id aliquam elit. Quisque vitae ultrices elit, id faucibus velit. Sed vel enim condimentum, euismod lacus egestas, scelerisque justo. In faucibus, nibh nec luctus ultricies, nisi quam tempus magna, non malesuada nisi lectus eu elit. Phasellus eget egestas orci.

Mauris tempus ipsum est, posuere volutpat dui cursus sed. Pellentesque et maximus orci. Mauris eu tincidunt tellus. Sed a mattis urna. Vivamus sed erat id purus congue convallis cursus vitae nisl. Vestibulum tristique scelerisque ex in ultricies. Quisque vel sem mattis, efficitur lorem et, eleifend lectus. Nam sit amet placerat tortor. Vivamus molestie orci scelerisque placerat semper. Vestibulum rutrum scelerisque nisl vel ultrices. Phasellus arcu nulla, faucibus quis porttitor ut, euismod nec mi. Pellentesque fermentum vestibulum nunc non auctor. Nulla vitae mi imperdiet, consequat mauris vitae, euismod nisi.

Phasellus in risus diam. Aenean suscipit tempor ex, sed feugiat eros pulvinar sit amet. Etiam ac nunc id neque vestibulum ullamcorper ut sed ante. Fusce in tortor leo. Pellentesque id varius ipsum. Mauris non eros gravida, lobortis risus vitae, mattis nisi. Aliquam molestie dictum ligula, quis elementum eros mattis vitae. Etiam vitae metus at leo finibus mattis. Curabitur convallis imperdiet lectus sed vestibulum. Proin in eros feugiat dui volutpat suscipit. Vestibulum laoreet non elit non auctor. Maecenas sit amet neque molestie, maximus mauris et, efficitur justo. Cras feugiat elit ut ante porta vehicula. Aliquam id convallis urna.

Vestibulum pretium id nunc sit amet tincidunt. Nullam consequat nisl orci, ut faucibus nisi efficitur eu. Maecenas eu fermentum quam. Fusce cursus mauris ut mi commodo malesuada. Curabitur sed ex laoreet odio sodales dignissim eget vel mauris. Nam tellus urna, condimentum nec neque eu, eleifend ullamcorper ligula. Proin eget lectus ligula. Donec dignissim ullamcorper lorem, ut vulputate turpis lobortis et. Praesent viverra tempor lorem quis suscipit. Curabitur luctus vel urna eget molestie. Praesent eros lorem, dictum in finibus sit amet, dignissim eget augue. Curabitur vestibulum elit eu dui semper condimentum. Phasellus vel neque in nibh fermentum fringilla nec sit amet lacus.

Integer convallis quam eget dui aliquet, egestas feugiat odio hendrerit. Praesent rhoncus, augue vel hendrerit tempor, nisl augue luctus velit, nec porttitor lacus velit quis metus. Morbi scelerisque viverra pretium. Sed imperdiet congue massa quis dignissim. Cras vestibulum dolor libero, nec ornare libero ultrices quis. Pellentesque viverra massa dolor, vel auctor eros maximus id. Duis vitae massa eget urna porttitor tincidunt. Nam pharetra, odio at suscipit ullamcorper, est lacus interdum enim, a posuere justo mauris sed urna. Curabitur vestibulum vitae est id sagittis. Nunc massa ante, dictum et est eget, viverra viverra velit. Suspendisse potenti. Sed posuere ut lectus non molestie. Donec tempus augue in odio sollicitudin, sit amet convallis velit blandit. In a lorem sodales, fringilla metus in, mollis ex. Etiam consectetur congue dui, vel faucibus purus mollis vitae.

Morbi feugiat sem elit, sodales dapibus arcu mollis et. Nulla tristique accumsan eros, vel sodales nibh accumsan id. In euismod maximus elit nec ornare. Donec varius tristique porttitor. Vestibulum at pulvinar diam, eget pharetra erat. Pellentesque vestibulum arcu in justo varius posuere vel et neque. Integer et purus vitae mauris cursus sagittis quis in purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quis lorem ante. Pellentesque faucibus auctor quam. Maecenas vehicula mi a odio facilisis pharetra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus vulputate aliquet odio. Aenean tincidunt nibh vel tortor auctor, et efficitur mi interdum. Nullam pharetra dolor nibh, quis fermentum nunc iaculis non. Donec tempor nisi tortor, et suscipit odio elementum nec.

Phasellus nec enim mi. Fusce vel felis sed quam malesuada sagittis. Proin efficitur interdum magna, non porta nulla tincidunt et. Integer cursus augue eget maximus fringilla. Suspendisse tristique bibendum urna ut aliquam. Pellentesque sed placerat nunc, at suscipit lorem. Suspendisse faucibus justo maximus dolor dictum, vestibulum scelerisque velit malesuada. Quisque non neque porta, consequat dolor eu, elementum libero. Phasellus in placerat nunc, at congue massa. Vivamus hendrerit urna ligula, non venenatis velit placerat id
`;